services:
  db:
    image: mysql:5.6
    container_name: prodputturvetsdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: db_stateputturjob
      MYSQL_USER: stateputturjob
      MYSQL_PASSWORD: StateputturJob@HitpL2025
    ports:
      - "3356:3306"
    volumes:
     - ./db_stateputturjob.sql:/docker-entrypoint-initdb.d/db_stateputturjob.sql
     - ./mysql/data:/var/lib/mysql
     - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - tomcat-network-prod-putturvets
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -pmysql123 -e 'SELECT 1'"]
      interval: 10s
      retries: 10
      start_period: 40s


  tomcat:
    build:
      context: .
    image: prodputturvetsimage:latest
    container_name: prodputturvetsapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: db_stateputturjob
      MYSQL_USER: stateputturjob
      MYSQL_PASSWORD: StateputturJob@HitpL2025
    volumes:
      - /opt/prodputturVet/images:/opt/prodputturVet/images
    ports:
      - "9056:8080"
    networks:
      - tomcat-network-prod-putturvets

networks:
  tomcat-network-prod-putturvets:
    driver: bridge
